# Generated by Django 5.1.15 on 2026-08-22 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(editable=False, max_length=50, unique=True)),
                ('verification_slug', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('learner_name_snapshot', models.CharField(max_length=255)),
                ('course_title_snapshot', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='certificates/')),
                ('final_score', models.PositiveIntegerField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='enrollment.enrollment')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_code', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('audience_code', 'year'), name='unique_cert_sequence')],
            },
        ),
    ]
