# Generated by Django 5.1.15 on 2026-09-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Short code, e.g. 'jamb', 'waec', 'trcn-pqe'.", max_length=30, unique=True)),
                ('name', models.CharField(help_text="Full name, e.g. 'JAMB UTME'.", max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='verification_status',
            field=models.CharField(choices=[('N_A', 'Not applicable'), ('VERIFIED', 'Verified — independent pass agreed'), ('DISPUTED', 'Disputed — independent pass disagreed, needs human review')], default='N_A', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='source_exam',
            field=models.ForeignKey(blank=True, help_text='Which real exam this question targets, if any (JAMB, WAEC, ...). Blank for ordinary course-quiz questions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessment.sourceexam'),
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text="e.g. 'Biology', 'Chemistry', 'Mathematics'.", max_length=100)),
                ('section', models.CharField(blank=True, help_text="e.g. 'A. Variety of Organisms' — the syllabus's own top-level grouping, if it has one.", max_length=255)),
                ('name', models.CharField(help_text="The specific topic, e.g. 'Nutrition' or 'Heredity — Sex-linked Characters'.", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text="Display order within the syllabus, roughly matching the official document's own sequence.")),
                ('source_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_topics', to='assessment.sourceexam')),
            ],
            options={
                'ordering': ['source_exam', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='syllabus_topics',
            field=models.ManyToManyField(blank=True, help_text='Real syllabus position(s) within source_exam — only meaningful when source_exam is set.', related_name='questions', to='assessment.syllabustopic'),
        ),
        migrations.AddConstraint(
            model_name='syllabustopic',
            constraint=models.UniqueConstraint(fields=('source_exam', 'subject', 'name'), name='unique_syllabus_topic_per_exam_subject'),
        ),
    ]
