# Generated by Django 5.1.15 on 2026-09-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_sourceexam_question_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='syllabus_topic_filter',
            field=models.ManyToManyField(blank=True, help_text='Scope this quiz to specific syllabus topics (question-bank-engine mock exams only).', related_name='quizzes', to='assessment.syllabustopic'),
        ),
    ]
