# Generated by Django 5.1.15 on 2026-08-23 00:47

import django.db.models.deletion
import django_ckeditor_5.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_course_delisted_reason_course_domain_reviewer'),
        ('organizations', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/photos/')),
                ('credentials', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('referral_code', models.SlugField(blank=True, unique=True)),
                ('own_traffic_rate', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5)),
                ('platform_traffic_rate', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('payout_bank_name', models.CharField(blank=True, max_length=255)),
                ('payout_account_number', models.CharField(blank=True, max_length=20)),
                ('payout_account_name', models.CharField(blank=True, max_length=255)),
                ('agreement_signed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement_version', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('APPLICANT', 'Applicant'), ('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('OFFBOARDED', 'Offboarded')], default='APPLICANT', max_length=20)),
                ('suspended_reason', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='instructors/documents/')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_documents', to='instructors.instructor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerInstructorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('LEARNER', 'Learner'), ('INSTRUCTOR', 'Instructor')], max_length=20)),
                ('body', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_messages', to='catalog.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_kobo', models.PositiveIntegerField(default=0)),
                ('amount_kobo', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('bank_reference', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('statement_pdf', models.FileField(blank=True, null=True, upload_to='instructors/payouts/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='instructors.instructor')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='EarningsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('SALE_GROSS', 'Sale (gross)'), ('PLATFORM_FEE', 'Platform fee'), ('INSTRUCTOR_EARNING', 'Instructor earning'), ('REFUND_REVERSAL', 'Refund reversal'), ('ADJUSTMENT', 'Adjustment'), ('PAYOUT_SENT', 'Payout sent')], max_length=20)),
                ('amount_kobo', models.IntegerField(help_text='Signed — credits positive, debits negative.')),
                ('attribution', models.CharField(blank=True, choices=[('OWN_TRAFFIC', 'Own traffic'), ('PLATFORM_TRAFFIC', 'Platform traffic')], max_length=20)),
                ('rate_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earnings_entries', to='catalog.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings_entries', to='organizations.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earnings_entries', to='payments.payment')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings_entries', to='instructors.instructor')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='instructors.payout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_open_for_applications', models.BooleanField(default=False)),
                ('reviewer_credentials_note', models.TextField(blank=True)),
                ('requires_legal_review', models.BooleanField(default=False)),
                ('domain_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('enrollments_30d', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('refund_rate_30d', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('complaint_count_30d', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('instructor_response_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('days_since_content_review', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='catalog.course')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('course', 'date'), name='unique_course_health_per_day')],
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review_text', models.TextField(blank=True)),
                ('instructor_response', models.TextField(blank=True)),
                ('instructor_responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_reason', models.CharField(blank=True, max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalog.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('course', 'user'), name='unique_rating_per_learner_per_course')],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes requested'), ('REJECTED', 'Rejected')], max_length=20)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('notes_to_instructor', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.course')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', '-round'],
                'constraints': [models.UniqueConstraint(fields=('course', 'round'), name='unique_course_review_round')],
            },
        ),
    ]
