# Generated by Django 5.1.15 on 2026-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='certificate_signatory_name',
            field=models.CharField(blank=True, help_text='Leave blank to use your display name above.', max_length=255),
        ),
        migrations.AddField(
            model_name='instructor',
            name='certificate_signatory_title',
            field=models.CharField(blank=True, help_text='Leave blank to show "Instructor".', max_length=255),
        ),
        migrations.AddField(
            model_name='instructor',
            name='certificate_signature_image',
            field=models.ImageField(blank=True, help_text='Optional — a photo/scan of your actual signature, ideally on a plain background.', null=True, upload_to='instructors/signatures/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='certificate_signature_mode',
            field=models.CharField(choices=[('NAME_TITLE', 'My name and title'), ('ORG_NAME_ONLY', 'Organization name only (no personal name)'), ('SIGNATURE_IMAGE', 'An uploaded signature image')], default='NAME_TITLE', help_text='How your signature reads on certificates for your own courses.', max_length=20),
        ),
    ]
