# Generated by Django 5.1.15 on 2026-09-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(blank=True, help_text="Where this lead was captured, e.g. 'footer', 'catalog' — free text, not a choice list, so a new capture point never needs a migration to add its own label.", max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
