# Generated by Django 5.1.15 on 2026-08-23 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='attributed_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributed_payments', to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='attribution',
            field=models.CharField(blank=True, choices=[('OWN_TRAFFIC', 'Own traffic'), ('PLATFORM_TRAFFIC', 'Platform traffic')], max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='attribution_source',
            field=models.CharField(blank=True, choices=[('REFERRAL_LINK', 'Referral link'), ('COUPON', 'Coupon'), ('DIRECT', 'Direct'), ('ORGANIC', 'Organic')], max_length=20),
        ),
    ]
