# Generated by Django 5.1.15 on 2026-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_attributed_instructor_payment_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('COURSE_ACCESS', 'Course access'), ('CERTIFICATE', 'Certificate')], default='COURSE_ACCESS', max_length=20),
        ),
    ]
