# Generated by Django 5.1.15 on 2026-09-12 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_lesson_generated_teaser_url'),
        ('licensing', '0002_diagnosticmocktest_diagnosticattempt_and_more'),
        ('payments', '0004_couponattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='institutional_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='licensing.institutionallicense'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='catalog.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('COURSE_ACCESS', 'Course access'), ('CERTIFICATE', 'Certificate'), ('INSTITUTIONAL_LICENSE', 'Institutional licence')], default='COURSE_ACCESS', max_length=30),
        ),
    ]
