# Generated by Django 5.1.15 on 2026-08-22 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='payments.partner'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('MANUAL', 'Manual'), ('COUPON', 'Coupon'), ('PARTNER', 'Partner referral')], default='MANUAL', max_length=20),
        ),
    ]
