# Generated by Django 5.1.15 on 2026-09-12 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_enrollment_partner_alter_enrollment_source'),
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='institutional_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='licensing.institutionallicense'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('MANUAL', 'Manual'), ('COUPON', 'Coupon'), ('PARTNER', 'Partner referral'), ('INSTITUTIONAL', 'Institutional licence seat')], default='MANUAL', max_length=20),
        ),
    ]
