# Generated by Django 5.1.15 on 2026-09-12 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0024_lesson_generated_teaser_url'),
        ('organizations', '0002_organization_certificate_signature_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('proprietor', models.ForeignKey(help_text="The proprietor's own login — will see the per-school dashboard.", on_delete=django.db.models.deletion.PROTECT, related_name='institutions_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seats', models.PositiveIntegerField(help_text='Total student seats this licence covers.')),
                ('term_starts_at', models.DateTimeField()),
                ('term_ends_at', models.DateTimeField(help_text='Enrollments created under this licence expire here.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending — not yet paid'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('amount_kobo', models.PositiveIntegerField(blank=True, help_text='Quoted price in kobo, once agreed with the proprietor.', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('courses', models.ManyToManyField(help_text="Which course(s) this licence's seats grant access to.", related_name='institutional_licenses', to='catalog.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licensing.institution')),
            ],
            options={
                'ordering': ['-term_starts_at'],
            },
        ),
    ]
