# Generated by Django 5.1.15 on 2026-09-12 19:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_quiz_syllabus_topic_filter'),
        ('licensing', '0001_initial'),
        ('organizations', '0002_organization_certificate_signature_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticMockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('question_count', models.PositiveIntegerField(default=20)),
                ('time_limit_minutes', models.PositiveIntegerField(default=30, help_text='0 = no time limit.')),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_tests', to='assessment.questionbank')),
                ('institution', models.ForeignKey(blank=True, help_text='Optional — set when this link was made for one prospect school, so their proprietor gets a school-level summary filtered to just their students. Blank = a general public diagnostic, shareable with anyone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_tests', to='licensing.institution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('syllabus_topic_filter', models.ManyToManyField(blank=True, help_text='Blank = pull from the whole bank.', related_name='diagnostic_tests', to='assessment.syllabustopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('question_snapshot', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('topic_breakdown', models.JSONField(blank=True, default=dict)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='diagnostic_reports/')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='licensing.diagnosticmocktest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField()),
                ('selected_choice_ids', models.JSONField(default=list)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='licensing.diagnosticattempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question_id'), name='unique_diagnostic_attempt_question')],
            },
        ),
    ]
