# Generated by Django 5.1.15 on 2026-08-22 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('engagement', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('default_severity', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('threshold_config', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('DIGEST', 'Daily digest'), ('INTERRUPT', 'Immediate interrupt')], default='DIGEST', max_length=20)),
                ('cooldown_days', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CalendarObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('obligation_type', models.CharField(choices=[('REGULATORY', 'Regulatory'), ('CONTRACTUAL', 'Contractual'), ('OPERATIONAL', 'Operational'), ('RENEWAL', 'Renewal')], max_length=20)),
                ('due_date', models.DateField()),
                ('lead_days', models.PositiveIntegerField(default=30, help_text='How far ahead to start warning.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('recurrence_rule', models.CharField(blank=True, help_text="e.g. 'yearly', 'quarterly' — informational for now, not auto-applied.", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='obligations/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100)),
                ('category', models.CharField(choices=[('MONEY', 'Money'), ('QUALITY', 'Quality'), ('LEARNER', 'Learner'), ('INSTRUCTOR', 'Instructor'), ('PARTNER', 'Partner'), ('SYSTEM', 'System'), ('LEGAL', 'Legal'), ('GROWTH', 'Growth')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('ATTENTION', 'Attention'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('subject_id', models.PositiveIntegerField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('SNOOZED', 'Snoozed'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissal_reason', models.CharField(blank=True, max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('decision_due', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-severity', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='InterruptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interrupt_logs', to='organizations.organization')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrupt_logs', to='operations.signal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_date', models.DateField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signal_count', models.PositiveIntegerField(default=0)),
                ('rendered_html', models.TextField(blank=True)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='engagement.emaillog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digest_runs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-run_date'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'run_date'), name='unique_digest_per_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['RESOLVED', 'DISMISSED']), _negated=True), fields=('dedupe_key',), name='unique_open_signal_dedupe_key'),
        ),
    ]
