# Generated by Django 5.1.15 on 2026-08-23 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_seed_default_signal_rules'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterruptBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interrupt_budgets', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'date'), name='unique_interrupt_budget_per_day')],
            },
        ),
    ]
