# Generated by Django 5.1.15 on 2026-08-22 21:23

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/covers/')),
                ('promo_video_id', models.CharField(blank=True, max_length=255)),
                ('audience', models.CharField(choices=[('BREEDER', 'Breeder'), ('VET', 'Veterinarian'), ('GENERAL', 'General')], max_length=20)),
                ('level', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='FOUNDATION', max_length=20)),
                ('price_ngn', models.PositiveIntegerField(default=0, help_text='Whole naira.')),
                ('compare_at_price_ngn', models.PositiveIntegerField(blank=True, help_text="Strike-through 'was' price. Leave blank if none.", null=True)),
                ('access_type', models.CharField(choices=[('LIFETIME', 'Lifetime'), ('TIMED', 'Timed')], default='LIFETIME', max_length=20)),
                ('access_months', models.PositiveIntegerField(blank=True, help_text='Required when access_type is TIMED.', null=True)),
                ('content_version', models.PositiveIntegerField(default=1, help_text='Bump when material is materially updated.')),
                ('free_update_months', models.PositiveIntegerField(default=12)),
                ('requires_final_assessment', models.BooleanField(default=False)),
                ('pass_mark', models.PositiveIntegerField(default=70)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['programme', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('unlock_rule', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('SEQUENTIAL', 'Sequential (previous module completed)'), ('DRIP_DAYS', 'Drip — days after enrollment')], default='SEQUENTIAL', max_length=20)),
                ('drip_days', models.PositiveIntegerField(default=0, help_text='Days after enrollment. Used only when unlock_rule is DRIP_DAYS.')),
                ('requires_quiz_pass_to_advance', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.course')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('TEXT', 'Text'), ('PDF', 'PDF'), ('DOWNLOAD', 'Download'), ('LIVE', 'Live session')], default='VIDEO', max_length=20)),
                ('video_provider', models.CharField(blank=True, choices=[('BUNNY', 'Bunny Stream'), ('CLOUDINARY', 'Cloudinary')], max_length=20)),
                ('video_id', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Used as the lesson content for TEXT lessons, and as notes otherwise.')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lessons/attachments/')),
                ('is_preview', models.BooleanField(default=False, help_text='Viewable without enrollment, for the sales page.')),
                ('transcript', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='catalog.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('audience', models.CharField(choices=[('BREEDER', 'Breeder'), ('VET', 'Veterinarian'), ('GENERAL', 'General')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='catalog.programme'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='catalog.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='catalog.module')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
