# Generated by Django 5.1.15 on 2026-08-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description. Falls back to subtitle if blank.', max_length=160),
        ),
        migrations.AddField(
            model_name='course',
            name='not_for',
            field=models.TextField(blank=True, help_text='Who this course is NOT for — one point per line.'),
        ),
        migrations.AddField(
            model_name='course',
            name='sales_headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='sales_subheadline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Who this course is for — one point per line.'),
        ),
    ]
