# Generated by Django 5.1.15 on 2026-08-23 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_course_delisted_reason_course_domain_reviewer'),
        ('instructors', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='last_content_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='next_content_review_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Internal — never shown on the public sales page.'),
        ),
        migrations.AddField(
            model_name='course',
            name='review_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('CHANGES_REQUESTED', 'Changes requested'), ('APPROVED', 'Approved'), ('DELISTED', 'Delisted')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='instructors.vertical'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), ('review_status', 'APPROVED'), _connector='OR'), name='course_publish_requires_approved_review_status'),
        ),
    ]
