# Generated by Django 5.1.15 on 2026-08-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_course_instructor_course_last_content_review_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='minimum_price_ngn',
            field=models.PositiveIntegerField(default=0, help_text="Only used when pricing_model is PAY_WHAT_YOU_WANT — the floor the buyer can't go under. 0 means a buyer can genuinely pay nothing."),
        ),
        migrations.AddField(
            model_name='course',
            name='pricing_model',
            field=models.CharField(choices=[('PAID', 'Paid — pay to access the course'), ('FREE', 'Free — course and certificate both free'), ('CERTIFICATE_PAID', 'Free course, paid certificate'), ('PAY_WHAT_YOU_WANT', 'Pay what you want — buyer names the price')], default='PAID', help_text='PAID: pay to access. FREE: course and certificate both free. CERTIFICATE_PAID: access is free, price_ngn is charged for the certificate instead.', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_ngn',
            field=models.PositiveIntegerField(default=0, help_text='Whole naira. Ignored (treated as 0) when pricing_model is FREE. Used as the suggested price when pricing_model is PAY_WHAT_YOU_WANT.'),
        ),
    ]
