# Generated by Django 5.1.15 on 2026-08-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_course_minimum_price_ngn_course_pricing_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, help_text='Learner must have COMPLETED this course before they can enroll in this one. Leave blank for no prerequisite.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unlocks', to='catalog.course'),
        ),
    ]
