# Generated by Django 5.1.15 on 2026-08-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_course_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='notify_on_publish',
            field=models.BooleanField(default=True, help_text='Fire the course-publish webhook (if configured) when a course in this Programme publishes.'),
        ),
    ]
