# Generated by Django 5.1.15 on 2026-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_mark_non_digital_programmes_no_publish_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='notify_on_publish',
        ),
        migrations.AddField(
            model_name='programme',
            name='webhook_line',
            field=models.CharField(choices=[('NONE', "None — publishing doesn't notify any external system"), ('DIGITAL', 'Digital line (Xpress Digital Academy campaign system)'), ('VET', 'Veterinary line (Xpress Vet Marketplace)')], default='NONE', help_text='Fires the matching course-publish webhook (if that destination is configured) when a course here publishes.', max_length=20),
        ),
    ]
