# Generated by Django 5.1.15 on 2026-08-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_gate_dog_breeding_advanced_behind_intermediate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_staff_training',
            field=models.BooleanField(default=False, help_text='Internal training course. Hidden from the public catalog and public course-detail page entirely (404s for anyone without is_staff) — used for onboarding/ongoing staff training rather than public course sales.'),
        ),
    ]
