# Generated by Django 5.1.15 on 2026-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_course_is_staff_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_compulsory_staff_training',
            field=models.BooleanField(default=False, help_text="Only meaningful when is_staff_training is also set. Every user is auto-enrolled in this course the moment they're added to any Django Group (see apps.accounts.signal_receivers) — the personal, sequential 'everyone goes through this as they join' track. Pace modules with unlock_rule=DRIP_DAYS so each person's journey runs from their own enrollment date, not a shared calendar date. Leave unchecked for one-off department/personal/emergency training that's assigned manually instead."),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_staff_training',
            field=models.BooleanField(default=False, help_text='Internal training course. Hidden from the public catalog entirely; the course-detail page 404s for anyone not enrolled (or not a superuser) — enroll someone via the Enrollment admin to grant access, same as any other course. Not is_staff-based: a trainee needs no Django-admin login rights at all.'),
        ),
    ]
