# Generated by Django 5.1.15 on 2026-08-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_course_is_compulsory_staff_training_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unlock_delay_days',
            field=models.PositiveIntegerField(default=0, help_text='Only relevant when prerequisite is set AND is_compulsory_staff_training is True: how many days after completing the prerequisite before this course auto-enrolls (see apps.engagement.tasks.advance_compulsory_training_chains_task). Course-to-course pacing for a compulsory training sequence — separate from Module.drip_days, which paces content within a single course.'),
        ),
    ]
