# Generated by Django 5.1.15 on 2026-08-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0017_course_unlock_delay_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_group',
            field=models.ForeignKey(blank=True, help_text="Only meaningful when is_compulsory_staff_training is also set. Leave blank for a track every staff member goes through regardless of role (e.g. General Onboarding). Set this to scope a role-specific compulsory course (e.g. Manager Onboarding, Instructor Onboarding) so only members of that one Group are auto-enrolled — without this, a second role-specific compulsory course would force every staff member through every role's training, not just their own.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_compulsory_courses', to='auth.group'),
        ),
    ]
