# Generated by Django 5.1.15 on 2026-09-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_course_required_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scene_type', models.CharField(choices=[('titleCard', 'Title card'), ('bulletReveal', 'Bullet reveal'), ('whiteboardDiagram', 'Whiteboard diagram'), ('fullImage', 'Full image'), ('workedExample', 'Worked example'), ('evidenceCard', 'Evidence card'), ('outroCard', 'Outro card')], max_length=20)),
                ('narration', models.TextField(blank=True, help_text='What the voiceover says during this scene. There is deliberately no duration field here — the video pipeline measures the actual generated audio (Kokoro while drafting, ElevenLabs for the final render) and times the scene to that, so this text is the only input that controls length.')),
                ('image', models.ImageField(blank=True, help_text="Source art for whiteboardDiagram (traced with potrace) or fullImage. Leave blank for scene types that don't use one.", null=True, upload_to='lessons/video-scenes/')),
                ('payload', models.JSONField(blank=True, default=dict, help_text="Scene-type-specific content, passed through to Remotion as-is: bullets (bulletReveal, workedExample steps), evidenceGrade + citation (evidenceCard), alt text (fullImage/whiteboardDiagram). One JSON field rather than a column per scene type's shape, so the visual side can iterate on exactly what a scene type needs without a migration here every time.")),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_scenes', to='catalog.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
