# Generated by Django 5.1.15 on 2026-09-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_videoscene'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='generated_video',
            field=models.FileField(blank=True, help_text="Uploaded by manage.py attach_generated_videos from video/out/ — the automated lecture-video pipeline's finished render for this lesson. Takes priority over video_provider/video_id on the lesson player when present.", null=True, upload_to='lessons/generated-video/'),
        ),
    ]
