# Generated by Django 5.1.15 on 2026-09-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_lesson_generated_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='generated_video_url',
            field=models.URLField(blank=True, help_text="Same as generated_video (automated lecture-video pipeline output) but hosted on Cloudinary instead of Supabase — uploaded by manage.py attach_generated_videos --cloudinary, a direct API call (see apps.catalog.cloudinary_upload), not through Django's storage abstraction, since this is an external URL, not a file Django itself stores. Checked BEFORE generated_video on the lesson player, so a lesson with both (shouldn't normally happen) prefers this one.", max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='generated_video',
            field=models.FileField(blank=True, help_text="Uploaded by manage.py attach_generated_videos from video/out/ — the automated lecture-video pipeline's finished render for this lesson, via Django's own storage (Supabase S3 in prod). Legacy path: Supabase's free tier is only 1GB, shared with certificates, so new uploads go through generated_video_url (Cloudinary) instead — see that field. Existing values here are left as-is, not migrated.", null=True, upload_to='lessons/generated-video/'),
        ),
    ]
