# Generated by Django 5.1.15 on 2026-09-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_lesson_generated_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text="Set by manage.py attach_to_youtube once this lesson's video (full for FREE courses, teaser only for PAID ones — see that command's own comment on why) is live on the Xpress Digital Academy YouTube channel. Blank means not yet uploaded; presence alone marks it done, so the command never re-uploads it.", max_length=32),
        ),
    ]
