# Generated by Django 5.1.15 on 2026-09-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_lesson_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, help_text="Set by manage.py attach_to_youtube the first time one of this course's lessons uploads — every subsequent upload for this course is added to the same playlist, so a viewer can watch the whole course in order on YouTube.", max_length=34),
        ),
    ]
