# Generated by Django 5.1.15 on 2026-09-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_course_youtube_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='generated_teaser_url',
            field=models.URLField(blank=True, help_text="The 30s vertical teaser (video/out/teasers/<track>/<slug>.mp4), hosted on Cloudinary — uploaded by manage.py attach_generated_videos --cloudinary --teasers. Only ever used for PAID courses (see attach_to_youtube's eligible_upload_kind): the full generated_video/generated_video_url is what a FREE course's lesson page shows, but only the teaser ever leaves the platform publicly for a paid course.", max_length=500),
        ),
    ]
