# Generated by Django 5.1.15 on 2026-09-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='How much this question is worth toward the total score.'),
        ),
    ]
