# Generated by Django 5.1.15 on 2026-08-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('primary_color', models.CharField(blank=True, help_text='Hex color, e.g. #1A73E8', max_length=7)),
                ('from_email', models.EmailField(help_text='Sender address used for all outbound email for this org.', max_length=254)),
                ('support_whatsapp', models.CharField(blank=True, max_length=32)),
                ('certificate_signature_image', models.ImageField(blank=True, null=True, upload_to='organizations/signatures/')),
                ('certificate_signatory_name', models.CharField(blank=True, max_length=255)),
                ('certificate_signatory_title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
